In [1]:
import numpy as np

In [2]:
W = np.random.rand(3,5)* 2 - 1
V = np.random.rand(5,2)* 2 - 1
X = np.random.rand(3,1)* 2 - 1
print(W)

[[ 0.23488124 -0.44593157 -0.8842194   0.89323277 -0.01788746]
 [ 0.28423015  0.26971351  0.66596958  0.71458173 -0.83931204]
 [ 0.7133614   0.54585308  0.83402313  0.6756496   0.17980306]]


W = np.random.rand(2,5)* 2 - 1
V = np.random.rand(5,1)* 2 - 1
X = np.random.rand(3,1)* 2 - 1
print(W)

In [3]:
def vd_nn(X,W,V):
    def af(x):
        y = np.tanh(x)
        return y
    net_h = W.T @ X  # --> Size (3,5) transpose to (5x3), (5x3) x (3x1) = Size 5x1
    y_h = af(net_h)
    output = V.T @ y_h # --> Size 2x1
    return output

y = vd_nn(X,W,V)
print(y)

[[-0.22950502]
 [ 0.5537226 ]]


def vd_nn(X,W,V):
    def af(x):
        y = np.tanh(x)
        return y
    net_h = W.T @ X  # --> Size (2,5) transpose to (5x2), (5x2) x (2x9) = Size 5x9
    y_h = af(net_h)
    output = V.T @ y_h # --> Size (5,1) tranpose to (1x5), (1x5) x (5x9) = 1x9
    return output

y = vd_nn(X,W,V)
print(y)

In [4]:
class vd :
    def __init__(self, X, W, V):
        self.X = X
        self.W = W
        self.V = V
    def af(self,x):
        Y = np.tanh(x)
        self.Y = Y
        return self.Y
    def callagain(self):
        y_h = self.af
        return y_h
    

g = vd(1,2,3)
j = g.af(5)
h = g.callagain
print(h)

<bound method vd.callagain of <__main__.vd object at 0x7f05647eaf90>>


In [5]:
Y = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3])
print(Y.shape)
Y_head = np.array([[0.10161529, 0.11495056, 0.12929388, 0.32399112, 0.38450365, 0.43198753, 0.54074041, 0.72197362, 0.86815218]])
print(Y_head.shape)
e = Y - Y_head
print(e)

(9,)
(1, 9)
[[0.89838471 0.88504944 0.87070612 1.67600888 1.61549635 1.56801247
  2.45925959 2.27802638 2.13184782]]


In [6]:
J = 1/9 * np.sum(e**2)
print(J)

2.88979679124565


In [13]:
W = np.random.rand(2,5)
W1 =  W * 2 - 1
print(W)
print(W1)

[[0.35538896 0.03053666 0.33937829 0.09136982 0.13983329]
 [0.61894579 0.56249776 0.06507241 0.18559761 0.14318207]]
[[-0.28922209 -0.93892669 -0.32124342 -0.81726037 -0.72033341]
 [ 0.23789157  0.12499552 -0.86985519 -0.62880478 -0.71363587]]
